# Generated by Django 3.2.8 on 2021-10-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comaterialesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(default='', max_length=30, verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='type_document',
            field=models.CharField(default='Cédula', max_length=30, verbose_name='typeDocument'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email'),
        ),
    ]
