# Generated by Django 3.2.8 on 2021-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comaterialesApp', '0002_auto_20211016_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(choices=[('A', 'Comfort S.A'), ('B', 'Decora S.A.S'), ('C', 'MultiHogar LTDA'), ('D', 'Corona S.A'), ('E', 'House S.A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(choices=[('A', 'Arlex'), ('B', 'artek'), ('C', 'fatboy'), ('D', 'Flos'), ('E', 'vitra')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
