# Generated by Django 3.2.8 on 2021-10-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comaterialesApp', '0003_auto_20211017_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('A', 'salas'), ('B', 'cocinas'), ('C', 'baños'), ('D', 'habitacion'), ('E', 'decoracion')], max_length=100),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(choices=[('A', 'comodidad'), ('B', 'natural'), ('C', 'ecologico'), ('D', 'Linea blanca')], max_length=100),
        ),
    ]
