# Generated by Django 3.2.8 on 2021-10-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comaterialesApp', '0004_auto_20211017_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('Salas', 'salas'), ('Cocinas', 'cocinas'), ('Baños', 'baños'), ('Habitación', 'habitacion'), ('Decoración', 'decoracion')], max_length=100),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(choices=[('Comodidad', 'comodidad'), ('Natural', 'natural'), ('Ecológico', 'ecologico'), ('Linea blanca', 'Linea blanca')], max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(choices=[('Comfort', 'Comfort S.A'), ('Decora', 'Decora S.A.S'), ('Multihogar', 'MultiHogar LTDA'), ('Corona', 'Corona S.A'), ('House', 'House S.A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(choices=[('Arlex', 'Arlex'), ('Artek', 'artek'), ('Fatboy', 'fatboy'), ('Flos', 'Flos'), ('Vitra', 'vitra')], max_length=50),
        ),
    ]
